[package]
name = "mmio_sifive_uart"
version = "0.1.0"
authors = ["Chris Williams <chrisw@diosix.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
